# Generated by Django 5.0.6 on 2024-06-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydroponicsystem',
            name='description',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='hydroponicsystem',
            name='name',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name='hydroponicsystem',
            name='plant_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
